[workspace]
resolver = "3"
members = [
    "rand_chacha",
    "rand_hc",
    "rand_isaac",
    "rand_jitter",
    "rand_pcg",
    "rand_sfc",
    "rand_xorshift",
    "rand_xoshiro",
]
exclude = [
    "benches",
]
